services:
  fastapi:
    image: ghcr.io/yamang02/ai_portfolio_agent_min:sha-{hash}
    ports:
      - "8000:8000"
    env_file: .env.production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
