services:
  fastapi:
    image: ghcr.io/yamang02/ai_portfolio_agent_min:staging
    ports:
      - "8001:8000"
    env_file: .env.staging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
